modelo de dados e views rest
codenation-dev/squad-1-ad-python-women-loadsmart-1 pull request #2
Opened 2019-10-13 14:21 UTC by carollzambelli

2019-10-13 16:12 UTC, polinelottin commented on api/models.py
> +class User(models.Model):
Precisamos salvar também o token do usuário? 

![image](https://user-images.githubusercontent.com/16206462/66718496-f9134380-edba-11e9-918d-ec2282adfb8e.png)

2019-10-13 16:59 UTC, leticiaFlorentinoPires commented on api/models.py
> +    password = models.CharField('password', max_length=50)
O que acham de por um validador já no model? Tipo aqui em baixo, acho elegante.
email = models.CharField('email', max_length=254, validators=[EmailValidator])
 password = models.CharField('password', max_length=50, validators=[MinValueValidator(limit_value=8)])

2019-10-13 17:06 UTC, leticiaFlorentinoPires commented on api/models.py
> +    last_login = models.DateField(default=date.today)
O DateField dá (year = 2018, month = 7, day = 12)
e o DateTimeField dá (year = 2018, month = 7, day = 12, hour = 7, minute = 9, second = 33)
Eu posso tá errada. Mas se for isso mesmo, seria melhor usar DateTimeField, vcs concordam?
Assim: last_login = models.DateTimeField('last_login',auto_now=True)

2019-10-13 17:13 UTC, leticiaFlorentinoPires commented on api/models.py
> +class User(models.Model):
Concordo!

2019-10-13 19:48 UTC, polinelottin requested changes
Carol, 

pelo papo que batemos com a @leticiaFlorentinoPires vamos seguir esse modelo aqui:

![image](https://user-images.githubusercontent.com/16206462/66720814-f1ae6300-edd7-11e9-9ad8-8f7bcfc8c98c.png)
https://drive.google.com/file/d/1HWNhk-hiIzFi5PfhkIPdVKZ7qXhRcW_s/view

## User
- Vamos incluir o `token` e a validação do tamanho mínimo do `password`

## Group
```
class Group(models.Model):
    name = models.TextField('name', max_length=50)
```

## GroupUser

Sugestão:
```
class GroupUser(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        null=True,
        related_name='groupuser'
    )

    group = models.ForeignKey(
        Group,
        on_delete=models.PROTECT,
        null=True,
        related_name='usergroup'
    )
```

## Agent

Sugestão:
```
class Agent(models.Model):
    level = models.CharField('level', max_length=20)
    env = models.CharField('env', max_length=20)
    address = models.GenericIPAddressField('address', protocol='IPv4')
    status = models.BooleanField('status')
```

## Event

Essa seria uma junção da tabela `Log` e `Event` que temos nesse PR. 

Sugestão:

```
class Event(models.Model):
    date = models.DateTimeField('date',  auto_now=True)
    title = models.CharField('title', max_length=200)
    detail = models.TextField('detail')
    archived = models.BooleanField('arquivado')

    agent = models.ForeignKey(
        Agent,
        on_delete=models.PROTECT,
        null=True,
        related_name='event'
    )

    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        null=True,
        related_name='event'
    )
```

2019-10-13 19:48 UTC, polinelottin commented on api/models.py
> +
Recebi uma review no meu código da semana 5 pedindo pra colocar um limite mínimo para a senha. Acho legal colocar aqui também. É só incluir esse código na linha 10:

````
def clean(self):
    from django.core.exceptions import ValidationError
        if len(self.password) < 8:
            raise ValidationError('Password must be greater than 8 characters')

2019-10-13 19:48 UTC, polinelottin commented on api/models.py
> +    codigo = models.IntegerField()
Não entendi o objetivo desse campo..

2019-10-13 19:48 UTC, polinelottin commented on api/models.py
> +    descricao = models.TextField('descricao')
Sugiro assumir o inglês como padrão:

`description`

2019-10-13 19:48 UTC, polinelottin commented on api/models.py
> +
Acho que falta o campo `address`, assim conseguimos informar o seguinte título na tela de detalhe do erro:

`Erro no <address> em  <date>`

![image](https://user-images.githubusercontent.com/16206462/66718646-886d2680-edbc-11e9-985d-3599047b7617.png)

2019-10-13 19:48 UTC, polinelottin commented on api/models.py
> +    date = models.DateField(default=date.today)
Será que aqui precisa ser `models.DateTimeField()`? Pergunto porque no título do detalhe do erro aparece a data e horário. 

![image](https://user-images.githubusercontent.com/16206462/66718763-e0585d00-edbd-11e9-94bf-96dddbe49726.png)

2019-10-13 19:48 UTC, polinelottin commented on api/models.py
> +    arquivado = models.BooleanField(default=False)
Sugiro assumir o inglês como padrão:

`archived`

2019-10-13 19:48 UTC, polinelottin commented on api/models.py
> +    password = models.CharField('password', max_length=50)
you rock, babe! tinha feito uma sugestão parecida:

```
def clean(self):
    from django.core.exceptions import ValidationError
        if len(self.password) < 8:
            raise ValidationError('Password must be greater than 8 characters')

2019-10-13 19:48 UTC, polinelottin commented on api/models.py
> +    last_login = models.DateField(default=date.today)
Isso mesmo @leticiaFlorentinoPires. Fiz a mesma observação para o campo `date` do `Event`

2019-10-14 00:43 UTC, closed without merging

2019-10-14 00:44 UTC, carollzambelli commented
vou fazer as alterações e abrir outro pr